---
version: 2.1

# -----------
#   ALIASES
# -----------
aliases:
  # --------------------
  #   ALIASES: Cache
  # --------------------
  yarn_cache_key: &yarn_cache_key yarn-v1-{{ checksum "yarn.lock" }}

  load_cache: &load_cache
    restore_cache:
      keys:
        - *yarn_cache_key

  save_cache: &save_cache
    save_cache:
      key: *yarn_cache_key
      paths:
        - ~/.cache/yarn
        - ~/.cache/Cypress
        - node_modules

  # -------------------
  #   ALIASES: Defaults
  # -------------------
  docker_test_stack: &docker_test_stack
    docker:
      - image: circleci/node:lts
        environment:
          NODE_ENV: test

# --------
#   JOBS
# --------
jobs:
  test_mocha:
    <<: *docker_test_stack
    steps:
      - checkout
      - *load_cache
      - run: yarn install --frozen-lockfile
      - *save_cache

      - run: yarn laboperator-middleware test --ci

      # Save test results for timing analysis
      - store_test_results:
          path: /tmp/reports

  ensure_compile:
    <<: *docker_test_stack
    steps:
      - checkout
      - *load_cache
      - run: yarn install --frozen-lockfile
      - *save_cache
      - run: yarn laboperator-middleware compile
      - run: |
          [[ -z $(git status -s) ]] || (echo "Don't forget to run 'yarn laboperator-middleware compile'" && exit 1)

# --------
#   WORKFLOWS
# --------
workflows:
  version: 2

  tests:
    jobs:
      - test_mocha
      - ensure_compile
