---
type: object
title: Middleware Configuration Schema
required:
  - laboperator
properties:
  laboperator:
    type: object
    required:
      - url
      - authentication
    properties:
      url:
        type: string
        format: uri
        pattern: '^https?://'
      authentication:
        type: object
        required:
          - token
        properties:
          token:
            type: object
            require:
              - url
            properties:
              url:
                type: string
                format: uri
                pattern: '^https?://'
              proxy:
                type: string
                format: uri
                pattern: '^https?://'
              options:
                type: object
                default: {}
                require:
                  - clientId
                  - clientSecret
                properties:
                  grantType:
                    type: string
                    enum:
                      - client_credentials
                      - password
                    default: client_credentials
                  scope:
                    type: string
                    default: read
                  clientId:
                    type: string
                  clientSecret:
                    type: string
                  redirectUri:
                    type: string
          tokenInfo:
            type: object
            require:
              - url
            properties:
              url:
                type: string
                format: uri
                pattern: '^https?://'
              proxy:
                type: string
                format: uri
                pattern: '^https?://'
additionalProperties:
  type: object
  required:
    - url
  properties:
    url:
      type: string
      format: uri
      pattern: '^https?://'
